import { EnemyType, EnemyStats } from '../../types'

export const enemyConfig: Record<EnemyType, EnemyStats> = {
  basic: {
    type: 'basic',
    name: 'Goblin',
    maxHP: 100,
    speed: 1,
    reward: 10,
    armor: 0,
    isFlying: false,
    isBoss: false,
    color: '#22c55e',
    size: 12,
    special: 'Standard enemy'
  },
  fast: {
    type: 'fast',
    name: 'Scout',
    maxHP: 60,
    speed: 2.5,
    reward: 15,
    armor: 0,
    isFlying: false,
    isBoss: false,
    color: '#eab308',
    size: 10,
    special: 'Moves quickly'
  },
  tank: {
    type: 'tank',
    name: 'Golem',
    maxHP: 500,
    speed: 0.5,
    reward: 30,
    armor: 5,
    isFlying: false,
    isBoss: false,
    color: '#78716c',
    size: 18,
    special: 'High HP, slow'
  },
  flying: {
    type: 'flying',
    name: 'Bat',
    maxHP: 80,
    speed: 1.5,
    reward: 20,
    armor: 0,
    isFlying: true,
    isBoss: false,
    color: '#a855f7',
    size: 10,
    special: 'Flies over obstacles'
  },
  stealth: {
    type: 'stealth',
    name: 'Shadow',
    maxHP: 70,
    speed: 1,
    reward: 25,
    armor: 0,
    isFlying: false,
    isBoss: false,
    color: '#64748b',
    size: 10,
    special: 'Invisible until close'
  },
  healer: {
    type: 'healer',
    name: 'Cleric',
    maxHP: 90,
    speed: 0.8,
    reward: 35,
    armor: 0,
    isFlying: false,
    isBoss: false,
    color: '#10b981',
    size: 12,
    special: 'Heals nearby enemies'
  },
  splitter: {
    type: 'splitter',
    name: 'Slime',
    maxHP: 120,
    speed: 0.7,
    reward: 40,
    armor: 0,
    isFlying: false,
    isBoss: false,
    color: '#14b8a6',
    size: 14,
    special: 'Splits into 2 on death'
  },
  shield: {
    type: 'shield',
    name: 'Guardian',
    maxHP: 150,
    speed: 0.6,
    reward: 25,
    armor: 10,
    isFlying: false,
    isBoss: false,
    color: '#3b82f6',
    size: 14,
    special: 'Has damage shield'
  },
  speedaura: {
    type: 'speedaura',
    name: 'Herald',
    maxHP: 80,
    speed: 1,
    reward: 30,
    armor: 0,
    isFlying: false,
    isBoss: false,
    color: '#f97316',
    size: 12,
    special: 'Speeds up nearby enemies'
  },
  boss_golem: {
    type: 'boss_golem',
    name: 'Stone Golem',
    maxHP: 2000,
    speed: 0.3,
    reward: 500,
    armor: 15,
    isFlying: false,
    isBoss: true,
    color: '#78716c',
    size: 30,
    special: 'Boss: high HP, slow'
  },
  boss_dragon: {
    type: 'boss_dragon',
    name: 'Dragon',
    maxHP: 1500,
    speed: 0.8,
    reward: 500,
    armor: 5,
    isFlying: true,
    isBoss: true,
    color: '#dc2626',
    size: 28,
    special: 'Boss: flies, fire breath'
  },
  boss_necromancer: {
    type: 'boss_necromancer',
    name: 'Necromancer',
    maxHP: 1000,
    speed: 0.5,
    reward: 500,
    armor: 0,
    isFlying: false,
    isBoss: true,
    color: '#7c3aed',
    size: 24,
    special: 'Boss: summons minions'
  }
}