// Terrain colors
export const GRASS_COLOR = '#4a7c23'
export const GRASS_DARK_COLOR = '#3d6a1c'
export const PATH_COLOR = '#c4a35a'
export const PATH_DARK_COLOR = '#a88942'
export const WATER_COLOR = '#3b82f6'
export const WATER_DARK_COLOR = '#2563eb'
export const ROCK_COLOR = '#6b7280'
export const ROCK_DARK_COLOR = '#4b5563'
export const ENTRY_COLOR = '#22c55e'
export const EXIT_COLOR = '#ef4444'

// Tower colors
export const TOWER_ARROW_COLOR = '#8b5cf6'
export const TOWER_CANNON_COLOR = '#374151'
export const TOWER_ICE_COLOR = '#06b6d4'
export const TOWER_FIRE_COLOR = '#f97316'
export const TOWER_LIGHTNING_COLOR = '#eab308'
export const TOWER_POISON_COLOR = '#84cc16'
export const TOWER_SNIPER_COLOR = '#6366f1'
export const TOWER_LASER_COLOR = '#ec4899'
export const TOWER_BOMB_COLOR = '#1f2937'
export const TOWER_SLOW_COLOR = '#67e8f9'
export const TOWER_GOLDMINE_COLOR = '#fbbf24'
export const TOWER_TESLA_COLOR = '#a855f7'

// Enemy colors
export const ENEMY_BASIC_COLOR = '#dc2626'
export const ENEMY_FAST_COLOR = '#f59e0b'
export const ENEMY_TANK_COLOR = '#7c3aed'
export const ENEMY_FLYING_COLOR = '#06b6d4'
export const ENEMY_STEALTH_COLOR = '#9ca3af'
export const ENEMY_HEALER_COLOR = '#10b981'
export const ENEMY_SPLITTER_COLOR = '#f43f5e'
export const ENEMY_SHIELD_COLOR = '#3b82f6'
export const ENEMY_SPEED_AURA_COLOR = '#f97316'
export const ENEMY_BOSS_COLOR = '#991b1b'

// Projectile colors
export const PROJECTILE_ARROW = '#a78bfa'
export const PROJECTILE_CANNON = '#1f2937'
export const PROJECTILE_ICE = '#67e8f9'
export const PROJECTILE_FIRE = '#fb923c'
export const PROJECTILE_LIGHTNING = '#fde047'
export const PROJECTILE_POISON = '#a3e635'
export const PROJECTILE_BULLET = '#fbbf24'
export const PROJECTILE_LASER = '#f472b6'

// UI colors
export const UI_BACKGROUND = 'rgba(15, 23, 42, 0.9)'
export const UI_PANEL = 'rgba(30, 41, 59, 0.95)'
export const UI_BORDER = '#334155'
export const UI_TEXT_PRIMARY = '#f8fafc'
export const UI_TEXT_SECONDARY = '#94a3b8'
export const UI_TEXT_MUTED = '#64748b'
export const UI_GOLD = '#fbbf24'
export const UI_LIVES = '#ef4444'
export const UI_HEALTH = '#22c55e'
export const UI_HEALTH_DAMAGED = '#eab308'
export const UI_BUTTON_PRIMARY = '#4f46e5'
export const UI_BUTTON_HOVER = '#6366f1'
export const UI_BUTTON_DANGER = '#dc2626'
export const UI_SUCCESS = '#22c55e'
export const UI_WARNING = '#f59e0b'

// Selection and hover
export const SELECTION_COLOR = '#f472b6'
export const HOVER_COLOR = 'rgba(244, 114, 182, 0.3)'
export const RANGE_INDICATOR = 'rgba(167, 139, 250, 0.2)'
export const RANGE_BORDER = 'rgba(167, 139, 250, 0.6)'
